language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: 
	- "pip install flaskr --use-mirrors"
	- "pip requests --use-mirrors"
# command to run tests
script: main