language: python
python:
  - 2.7
  - 3.2
env:
  - FLASK=0.8
  - FLASK=0.9
# command to install dependencies
install: 
  - pip install -q Flask==$FLASK --use-mirrors
  - pip install -q -e . --use-mirrors
# command to run tests
script: 
  - python setup.py