language: python
python:
  - 2.5
  - 2.6
  - 2.7
env:
  - FLASK=0.8
  - FLASK=0.9
# notifications
notifications:
  email: false
# command to install dependencies
install: 
  - pip install -q Flask==$FLASK --use-mirrors
  - pip install -q -e . --use-mirrors
# command to run tests
script: 
  - python setup.py install
  - python setup.py test